//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessIncentives.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColoradoBusiness
    {
        public long EntityId { get; set; }
        public string EntityName { get; set; }
        public string PrincipalAddress1 { get; set; }
        public string PrincipalAddress2 { get; set; }
        public string PrincipalCity { get; set; }
        public string PrincipalState { get; set; }
        public string PrincipalZipCode { get; set; }
        public string PrincipalCountry { get; set; }
        public string EntityStatus { get; set; }
        public string JurisdictionOfFormation { get; set; }
        public string EntityType { get; set; }
        public Nullable<System.DateTime> EntityFormDate { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
