//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessIncentives.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomOpportunity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomOpportunity()
        {
            this.Users = new HashSet<User>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public Nullable<short> FundingLevelID { get; set; }
        public string FundingLevelDetails { get; set; }
        public Nullable<int> AssistanceTypeID { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string WebLink { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string EligibilityKeywords { get; set; }
        public string Origin { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual AssistanceType AssistanceType { get; set; }
        public virtual FundingLevel FundingLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
