//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessIncentives.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramView
    {
        public int DeadlineDefined { get; set; }
        public Nullable<System.DateTime> ExtractedDeadline { get; set; }
        public string ProgramNumber { get; set; }
        public string ProgramTitle { get; set; }
        public string PopularName_020 { get; set; }
        public string FederalAgency_030 { get; set; }
        public string Authorization_040 { get; set; }
        public string Objectives_050 { get; set; }
        public string TypesOfAssistance_060 { get; set; }
        public string UsesAndUseRestrictions_070 { get; set; }
        public string ApplicantEligibility_081 { get; set; }
        public string BeneficiaryEligibility_082 { get; set; }
        public string CredentialsDocumentation_083 { get; set; }
        public string PreapplicationCoordination_091 { get; set; }
        public string ApplicationProcedures_092 { get; set; }
        public string AwardProcedure_093 { get; set; }
        public string Deadlines_094 { get; set; }
        public string RangeOfApprovalDisapprovalTime_095 { get; set; }
        public string Appeals_096 { get; set; }
        public string Renewals_097 { get; set; }
        public string FormulaAndMatchingRequirements_101 { get; set; }
        public string LengthAndTimePhasingOfAssistance_102 { get; set; }
        public string Reports_111 { get; set; }
        public string Audits_112 { get; set; }
        public string Records_113 { get; set; }
        public string AccountIdentification_121 { get; set; }
        public string Obligations_122 { get; set; }
        public string RangeAndAverageOfFinancialAssistance_123 { get; set; }
        public string ProgramAccomplishments_130 { get; set; }
        public string RegulationsGuidelinesAndLiterature_140 { get; set; }
        public string RegionalOrLocalOffice_151 { get; set; }
        public string HeadquartersOffice_152 { get; set; }
        public string WebsiteAddress_153 { get; set; }
        public string RelatedPrograms_160 { get; set; }
        public string ExamplesOfFundedProjects_170 { get; set; }
        public string CriteriaForSelectingProposals_180 { get; set; }
        public string PublishedDate { get; set; }
        public string ParentShortname { get; set; }
        public string URL { get; set; }
        public string Recovery { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
